apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lamiso
  name: lamiso
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lamiso
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lamiso
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}