apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lamiso
  name: lamiso
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lamiso
status:
  loadBalancer: {}
